<a href="https://colab.research.google.com/github/awangberg/Math242_Linear_algebra_code_projects/blob/master/Gram_Schmidt_Process.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [5]:
#  Create a vector:
r = np.matrix('1; 2; 3; 4')
r

matrix([[1],
        [2],
        [3],
        [4]])

In [6]:
r.dot()

ValueError: ignored

In [8]:
# create a vector as an array:
s = np.array([ 1, 2, 3, 4])
s

array([1, 2, 3, 4])

In [9]:
#do a dot product:
s.dot(s)

30

In [13]:
# the size of s:
np.sqrt(s.dot(s))

5.477225575051661

Using the Gram-Scmidt Orthonormalization Process


In [22]:
# the messy vectors:
r1 = np.array([  2, 4, 0, 0 ])
r2 = np.array([  1, 2, 3, 6 ])
r3 = np.array([  2, -1, 2, -1])
r4 = np.array([  1, 2,  3, 4])
r4

array([1, 2, 3, 4])

In [30]:
#   Find the first nice basis vector:
t1 = r1
#   Subtract off the nice basis vectors:
#   Nothing yet!

#  Find the magnitude of t1:
n1 = np.sqrt(t1.dot(t1))

#  So, u1 = (1/n1) * t1
u1 = (1/n1) * t1
u1

array([0.4472136 , 0.89442719, 0.        , 0.        ])

In [31]:
# Verify that u1 has size 1 and is orthogonal to all other u vectors:

u1.dot(u1)

0.9999999999999999

In [35]:
#   Find the second nice basis vector:
r2
#   Subtract off the nice basis vectors:
t2 = r2 - r2.dot(u1)   * u1
t2

##  Find the magnitude of t1:
n2 = np.sqrt(t2.dot(t2))
n2

##  So, u2 = (1/n2) * t2
u2 = (1/n2) * t2
u2

array([0.        , 0.        , 0.4472136 , 0.89442719])

In [39]:
#Check
print("The (squared) size of u2 = ", u2.dot(u2))
print("u2.u1 = ", u2.dot(u1))

The (squared) size of u2 =      1.0000000000000002
u2.u1 =  0.0


In [40]:
#   Find the third nice basis vector:
r3
#   Subtract off the nice basis vectors:
t3 = r3 - r3.dot(u1)   * u1   -  r3.dot(u2)  * u2
t3

##  Find the magnitude of t3:
n3 = np.sqrt(t3.dot(t3))
n3

##  So, u3 = (1/n3) * t3
u3 = (1/n3) * t3
u3

array([ 0.63245553, -0.31622777,  0.63245553, -0.31622777])

In [41]:
#Check
print("The (squared) size of u3 = ", u3.dot(u3))
print("u3.u1 = ", u3.dot(u1))
print("u3.u2 = ", u3.dot(u2))

The (squared) size of u3 =  1.0
u3.u1 =  -2.6816343567205363e-18
u3.u2 =  1.772118218877028e-17


In [43]:
#  Check that u3 = [ 2/sqrt(10), -1/sqrt(10), 2/sqrt(10), -1/sqrt(10)]
np.sqrt(10)*u3

array([ 2., -1.,  2., -1.])