<a href="https://colab.research.google.com/github/awangberg/Math242_Linear_algebra_code_projects/blob/master/svd_for_two_point_clusters.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [ ]:
#Let's create 10 points, centered around (3, 1) and (-1, 0)
#  (3, 1)
#  (3.25, 1.25)
#  (3.25, 0.75)
#  (2.75, 1.25)
#  (2.75, 0.75)
#  (-1, 0)
#  (-1.25, 0.25)
#  (-1.25, -0.25)
#  (-.75, 0.25)
#  (-0.75, -0.25)

#  We'll find the best-fit line y = b + mx.  Or
#  we can use:   b + mx - y = 0
#  So, the matrix involves rows of [ 1  x  -y ] entries.

M = np.matrix([[ 1, 3, -1],
               [ 1, 3.25, -1.25 ],
               [ 1, 3.25, -0.75 ],
               [ 1, 2.75, -1.25 ],
               [ 1, 2.75, -0.75],
               [ 1, -1, 0 ],
               [ 1, -1.25, -0.25],
               [ 1, -1.25, 0.25], 
               [ 1, -.75, -0.25],
               [ 1, -0.75, 0.25] ])

M

matrix([[ 1.  ,  3.  , -1.  ],
        [ 1.  ,  3.25, -1.25],
        [ 1.  ,  3.25, -0.75],
        [ 1.  ,  2.75, -1.25],
        [ 1.  ,  2.75, -0.75],
        [ 1.  , -1.  ,  0.  ],
        [ 1.  , -1.25, -0.25],
        [ 1.  , -1.25,  0.25],
        [ 1.  , -0.75, -0.25],
        [ 1.  , -0.75,  0.25]])

In [ ]:
M = np.matrix([[ 3 - 2, 1 - .5],
               [ 3.25 -2 , 1.25 - .5 ],
               [ 3.25 - 2, 0.75  - .5],
               [ 2.75 - 2, 1.25  - .5],
               [ 2.75 - 2, 0.75  - .5],
               [ -1 - 2, 0  - .5],
               [ -1.25 - 2, 0.25  - .5],
               [ -1.25 - 2, 0.25  - .5], 
               [ -.75 - 2, 0.25  - .5],
               [ -0.75 - 2, 0.25  - .5] ])

MM = M.transpose() * M

MM

M = np.matrix([[ 3, 1], [ -1, 0]])
MM = M.transpose() * M

MM


matrix([[10,  3],
        [ 3,  1]])

In [ ]:
np.linalg.eig(MM)

(array([10.90832691,  0.09167309]), matrix([[ 0.95709203, -0.28978415],
         [ 0.28978415,  0.95709203]]))

In [ ]:
np.linalg.svd(M)

(matrix([[-0.95709203,  0.28978415],
         [ 0.28978415,  0.95709203]]),
 array([3.30277564, 0.30277564]),
 matrix([[-0.95709203, -0.28978415],
         [-0.28978415,  0.95709203]]))